CREATE DATABASE CRUD_CURRICULO;
USE CRUD_CURRICULO;

select * from Pessoa;

CREATE TABLE PESSOA
(
	ID_PESSOA INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR (50),
	DATA_NASCIMENTO DATE,
	CPF CHAR (14),
	TELEFONE VARCHAR (12),
	EMAIL VARCHAR (50),
	FOTO IMAGE,
	ENDERECO VARCHAR(50),
	NUMERO_CASA CHAR (4)
);

CREATE PROC SPINSERIR_PESSOA
	@ID_PESSOA INT OUTPUT,
	@NOME VARCHAR (50),
	@DATA_NASCIMENTO DATE,
	@ENDERECO Varchar(50),
	@NUMERO_CASA CHAR(4),
	@CPF VARCHAR(14),
	@TELEFONE VARCHAR(12),
	@EMAIL VARCHAR(50),
	@FOTO IMAGE
	AS
	INSERT INTO PESSOA (NOME, DATA_NASCIMENTO, NUMERO_CASA, ENDERECO, CPF, TELEFONE, EMAIL, FOTO) VALUES (@NOME, @DATA_NASCIMENTO, @NUMERO_CASA, @ENDERECO, @CPF, @TELEFONE, @EMAIL, @FOTO)
GO

CREATE PROC spbuscar_pessoa_nome
	@textbuscar VARCHAR(50)
	AS SELECT * FROM PESSOA 
	WHERE NOME=@textbuscar
go

CREATE PROC SPBUSCAR_PESSOA
	AS
	SELECT TOP 100 FOTO, ID_PESSOA, NOME, DATA_NASCIMENTO, CPF, TELEFONE, EMAIL, NUMERO_CASA FROM PESSOA
	ORDER BY ID_PESSOA DESC
GO

create proc spdeletarPessoa_apresentacao
@id int
as 
delete from PESSOA where
ID_PESSOA=@id
go

CREATE PROC SPALTERAR_PESSOA
    @NOME VARCHAR(45),
	@ID_PESSOA INT,
	@ENDERECO VARCHAR(45),
	@DATA_NASCIMENTO DATE,
	@NUMERO_CASA CHAR (4),
	@CPF CHAR (14),
	@TELEFONE VARCHAR (12),
	@EMAIL VARCHAR (50)
	AS
	UPDATE PESSOA SET NOME=@NOME, ENDERECO=@ENDERECO, DATA_NASCIMENTO = @DATA_NASCIMENTO, NUMERO_CASA = @NUMERO_CASA, CPF = @CPF, TELEFONE=@TELEFONE, EMAIL = @EMAIL
	WHERE ID_PESSOA=@ID_PESSOA
GO

CREATE PROC spbuscar_morador_id
	@textbuscar VARCHAR(50)
	AS SELECT * FROM Pessoa
	WHERE ID_PESSOA=@textbuscar
GO